### ISSUE TITLE
Vulkan ?

### ISSUE THREAD

**Issue by gedw99** [go-gl/gl#30] opened 2015-11-16 20:22 UTC
Nvidea has released drivers. And the open source Intel drivers are almost named.

No spi yet. 
Also I saw the golang/mobile team are thinking about vulkan.

So what do you think ? Kind of itching this get going in Vulcan.

**Comment by Jragonmiris** [comment] 2015-11-17 06:01
It may not be a good idea to have a `go-Vulkan`. The thing with Vulkan is that it's an incredibly fine-grained API that's mostly meant to be used as a basis by middleware makers. This means that you make a LOT of function calls to get anything done, so the whole "suspend the runtime to call a C function" thing would start to add up very quickly in a way it doesn't in OpenGL.

Due to Vulkan by design being a bit more thread-friendly than GL, it would likely be good for a hypothetical Go graphics library, where a lot of utility functions are written in C and "glob called" by Go, but I don't think a straight-up naive bindgen Go-Vulkan port is a good plan.

**Comment by gedw99** [comment] 2015-11-17 07:09
@Jragonmiris i see your point about not mapping the API one to one to the C API.
I saw that the golang /mobile team are thinking about incorporating Vulkan, from what i read on their github issues.

Also because of the command buffers, goroutines are a perfect match to ensure all CPU cores are used.

Also according to the latest info from Kronos, Vulkan will also incorporate Windows creation cross platform. That means no GLUT etc.
Its really all encompassing which i think is awesome.

LunarG, also have a closed forum to help developers get going. Its called LunarXchange
https://www.phoronix.com/scan.php?page=news_item&px=LunarG-LunarXchange-Announce

I am trying to get access.

**Comment by shurcooL** [comment] 2015-11-19 08:03
I think Vulkan is going to involve a lot more experimentation than things we've seen in the past.

I think it's valuable to equip yourself with as much information about it before going in, but nothing should stop you from giving it a try and building something. If it works out well and leads to something useful, then it's a win.

I can share my near term plans and I don't currently plan to tackle this. I do find it interesting and will be keeping an eye on ongoing efforts. :)

**Comment by gedw99** [comment] 2015-11-19 11:24
@shurcooL 
thanks for your feedback. Good to see how others are approaching this.

The other problem will be that most desktops and mobiles will not have vulcan drivers. 
It will take a new generation of products to be rolled out, before Vulcan can be a target for a real world project.
Please correct me if i am off base here !!!
I did read how NVideo have updated their drivers for Vulcan recently though.

Last thing is IOS and OSX. IOS in their infinite wisedom have done their own route, and taken Mantle and rebranded it "New fancy graphics thingy". Its basically vulcanish it seems.
So it should be possible for a decent Vulcan golang code base to be developer to work irrespective.
Might require design time changes, OR maybe some runtime sniffing.

**Comment by acterhd** [comment] 2016-02-19 15:37
Vulkan please!

**Comment by gedw99** [comment] 2016-02-19 16:16
And so its starts :)

I would really like to use golang with Vulkan. The concurrency that Vulkan requires to work with it is a good fit for golang. Command Buffers in Vulkan seem a nice match to Channel Buffers in Golang.

**Comment by pwaller** [comment] 2016-02-19 16:25
Did you mean to close it?

**Comment by gedw99** [comment] 2016-02-19 17:39
No :)
Opps

**Comment by Jragonmiris** [comment] 2016-02-19 18:19
I also opened a thread on the mailing list about this, since I'm not entirely sure the issue tracker is the right place.

My opinion is still that Vulkan is far, far too fine grained to be usable with Go. It's meant as a backend for middleware, and after seeing the example code they posted I'm even more convinced it'd be a mistake to do a straight wrapping of Vulkan in Go.

https://groups.google.com/forum/#!topic/go-gl/N4EXB22yaq8

**Comment by Jragonmiris** [comment] 2016-02-19 18:22
I would also heavily recommend against *trying* Vulkan unless you're doing it for fun (and not something you want to finish). It's really, really a "so... you want to write your own OpenGL" (or even "so... you want to write your own portable graphics card driver") tool. It is not user friendly; it's a ton of fiddly struct field setting and boilerplate.

It's easy to get excited about things like concurrent command buffers, but you're not going to have a good day moving to Vulkan just to deal with goroutines via command buffers (which require semaphore managing semantics I haven't quite figured out yet).

Seriously, the "Hello, triangle!" program is upwards of 1000 lines I think.

**Comment by shurcooL** [comment] 2016-02-19 19:51
Yeah, there's a useful chart for deciding whether to use Vulkan.

https://twitter.com/renderpipeline/status/699501481632886786

**Comment by gedw99** [comment] 2016-02-22 16:46
Wow 1000 lines for a freaking triangle. 

I looked at the Google groups link, but no demo code.

I am wondering if the boilerplate beast can be slayed with design time code gen via templates ?
But without seeing demo code its impossible to make a decision.

Also can mix in a bit of runtime refection based code too if needed.

**Comment by gedw99** [comment] 2016-02-22 16:48
Geez this person has been busy !
Reams of demo code in CPP:https://github.com/SaschaWillems/Vulkan

**Comment by Jragonmiris** [comment] 2016-02-22 18:37
That's why it's meant for middleware. The reason Hello Triangle is so long is because you have to tell the driver a bunch of things about rendering that OpenGL automatically assumes/sets for you. Things like memory layouts and setting up command buffers and whatnot. This is what makes Vulkan fast, but also verbose. You have very fine control over fiddly details, but it also means that you have to set this all up yourself instead of having it dictated for you.

Of *course* you can make library functions and generators for all the boilerplate based on predetermined settings, that's what middleware does. :)

The examples I was referring to can be downloaded from khronos.org/vulkan

**Comment by michael-nischt** [comment] 2016-03-28 14:05
So there's Vulkan for
* [C++](https://github.com/nvpro-pipeline/vkcpp)
* [C#](https://github.com/mono/VulkanSharp)
* [Java](https://github.com/LWJGL/lwjgl3/tree/master/modules/core/src/main/java/org/lwjgl/vulkan)
* [Rust ](https://github.com/tomaka/vulkano)

Really a pity that Go is lagging behind or omitted.

**Comment by pwaller** [comment] 2016-03-28 21:42
@michael-nischt those contributing to these repositories (under the go-gl organization) don't represent all go developers, just a tiny facet of the community. And this facet grew up and became productive before Vulcan came onto the scene.

When we found go didn't have many nice OpenGL libraries - because they hadn't been made yet - we made them, and shared them here. You can see that there is a debate about whether to develop some now, but really it's only going to happen if someone wants to scratch an itch. It seems the itch isn't itchy enough to do so yet, but that might change.

You've also got some experienced people chipping in and saying that the trade-offs to be made aren't so great at the moment. It's probably worth considering those opinions unless you're experienced enough to knock out some bindings of your own anyway.

We gladly welcome newcomers and contributions, if you feel like contributing.

**Comment by hydroflame** [comment] 2016-05-08 10:47
@gedw99 @michael-nischt @acterhd I'm part of go-gl group but since we disagree on some things (eg. if we should have vulkan wrapper) I started working on these things at github.com/go-khronos

**Comment by joeblew99** [comment] 2016-05-09 13:55
Thanks for the heads up. Will watch that repo then.

**Comment by Kissaki** [comment] 2016-06-04 20:01
@gedw99 says he did not mean to close this ticket, yet it has remained closed for months even after that. If it was not meant to be closed, could you reopen it? Or am I missing something?

**Comment by gedw99** [comment] 2016-06-04 20:06
The itch to do this is not itchy anymore. I found a new itch :)

**Comment by pwaller** [comment] 2016-06-05 12:01
I think we can close this issue for now, since there is nothing much actionable remaining. @hydroflame has started [go-khronos](https://github.com/go-khronos/). Further discussion may be better had over there for now.

If/when that reaches stability and usefulness the community can decide whether moving the bindings to the go-gl or not.

**Closed by pwaller** 2016-06-05 12:01 UTC

**Comment by snuk182** [comment] 2016-06-23 22:04
Seems like go-kronos is dead.

**Comment by pwaller** [comment] 2016-06-24 11:32
Paging @hydroflame - did it move, or did you conclude it was too slow/difficult, or? (Re: https://github.com/go-gl/glow/issues/76#issuecomment-218978636)

**Comment by 4ydx** [comment] 2016-07-05 02:20
Did anybody happen to fork the vulkan repo that hydroflame was working on?  I would like to get a copy so that I could try to understand what he was originally doing.

**Comment by Kissaki** [comment] 2016-07-05 06:21
The idea is/was to use the machine-readable data provided by Khronos (machine readable spec/API) and generate go code from it, just like for OpenGL. You may want to check Go code for OpenGL for reference, which is also generated from the corresponding Khronos standard and machine readable data.

**Comment by xlab** [comment] 2016-08-17 10:52
You're welcome guys. Having VGo is a great deal actually, however I still agree that automatic CGo bindings for that is a naive idea. But since we have a working base now, anyone can start rewriting hot paths to be as efficient as possible.

https://github.com/vulkan-go/vulkan
https://github.com/vulkan-go/demos
