### ISSUE TITLE
ARM Architecture

### ISSUE THREAD

**Issue by shingtaklam1324** [go-gl/gl#84] opened 2017-09-09 12:53 UTC
Is there anyway to cross-compile/ compile go-gl to work on linux/arm?

**Comment by shurcooL** [comment] 2017-09-09 18:47
This is a duplicate of issue #76, let's continue the discussion there. Please see if that thread answers your question, and post a comment in that issue if not.

**Closed by shurcooL** 2017-09-09 18:47 UTC
Labels: duplicate, question
