### ISSUE TITLE
segmentation fault (goroutine related?)

### ISSUE THREAD

**Issue by dtromb** [go-gl/gl#29] opened 2015-10-07 01:29 UTC
I'm using some off-thread key event queuing, to provide smooth frame rate during processing (key processing takes place off in a different thread after a quick poll through glfw which simply enqueues the key event.)

This works fine, except if I mash on the keyboard a bunch:  rapid keypresses (and therefore rapid calls to my glfw key event callback) reliably produce a segmentation fault in the next buffer swap after the event poll call that queued them.   It looks like this:

```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x100000000 pc=0x7f049fcc8db0]

runtime stack:
runtime.throw(0x8c1480, 0x2a)
	/usr/lib/golang/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
	/usr/lib/golang/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x422ac0, 0xc820221d50, 0x0)
	/usr/lib/golang/src/runtime/cgocall.go:120 +0x11b fp=0xc820221d20 sp=0xc820221cf0
github.com/go-gl/glfw/v3.1/glfw._Cfunc_glfwSwapBuffers(0x22a5280)
	??:0 +0x31 fp=0xc820221d50 sp=0xc820221d20
github.com/go-gl/glfw/v3.1/glfw.(*Window).SwapBuffers(0xc82001c200)
	/home/dtrombley/go/src/github.com/go-gl/glfw/v3.1/glfw/context.go:40 +0x24 fp=0xc820221d60 sp=0xc820221d50
main.main()
	/home/dtrombley/go/src/wc/main/main.go:131 +0xb82 fp=0xc820221f40 sp=0xc820221d60
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:111 +0x2b0 fp=0xc820221f90 sp=0xc820221f40
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820221f98 sp=0xc820221f90

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [chan receive]:
wc.(*KeyEventQueue).run(0xc8200145a0)
	/home/dtrombley/go/src/wc/input.go:63 +0xe2
created by wc.StartKeyEventQueue
	/home/dtrombley/go/src/wc/input.go:39 +0x181
Error: process exited with code 2.
```

My main routine is a simple glfw.PollEvents(), followed by some GL drawing primitives (no errors), followed by a window.SwapBuffers(), followed by a non-blocking pull of key events from the channel pumped into (the pump to channel is the second goroutine in the traceback) from the queue.

We never reach that last part - the SwapBuffers() panics.   Reliably, and only if the keyboard is mashed (many keypresses per poll cycle - single keypresses and no keypresses work fine...)

**Comment by tapir** [comment] 2015-10-07 06:08
Can you share a simplified code that can reproduce this?

Also looks like this should be in go-gl/glfw issues not gl.

**Comment by pwaller** [comment] 2015-10-07 07:35
I agree with @tapir. Without showing your code, you are asking us to debug your code without being able to look at it. :smile: 

Where are you getting your keyboard input from? Are you calling glfw functions for that? If so, it's likely that is not a valid thing to do, since usually calls to glfw must all happen from the same thread.

I'm going to close this one for now. If you can provide reproducer code, please create a new issue over on go-gl/glfw. Also consider posting to our [mailing list go-gl@googlegroups.com](https://groups.google.com/forum/#!forum/go-gl).

**Closed by pwaller** 2015-10-07 07:35 UTC

**Comment by Jragonmiris** [comment] 2015-10-07 08:50
I'd say it's probably that the polling Goroutine hasn't been locked with
runtime.LockOSThread. Mashing the keys probably causes that goroutine to
block on input which causes the runtime to spawn another thread which it
then schedules the goroutine on next time it runs.

**Comment by MaVo159** [comment] 2015-10-21 14:12
I see the same error with a minimal example:
Program: http://paste.debian.net/317271/
A couple of support functions: http://paste.debian.net/317272/
Vertex shader: http://paste.debian.net/317272/
Fragment shader: http://paste.debian.net/317273/

The crash happens every couple of runs in every program I have written with go-gl/glfw on multiple machines. The only thing they have in common is that they use the official AMD driver on Debian (but different graphics card models).
The crash happens either instantaneously after starting the program or never (so probably only on the first SwapBuffers call).

**Comment by Jragonmiris** [comment] 2015-10-21 14:16
Is it possible that either Debian or the AMD driver is anal about display
contexts being on the main thread? I know that's a problem on OSX so you
need to call LockOSThread from `init` rather than `main`.

**Comment by shurcooL** [comment] 2015-10-21 15:57
> I know that's a problem on OSX so you need to call LockOSThread from `init` rather than `main`.

Yeah, in order to guarantee that `main` will be on main system thread, you need to call `LockOSThread` in `init`. Calling it in `main` is too late, even if it's the first statement, as the thread may switch away from main by that time.

That is a requirement on all platforms. However, as any race-condition-like thing, you may not run into issues if you skip it, but it's just not guaranteed to work in all cases.

**Comment by MaVo159** [comment] 2015-10-22 11:50
Did that, same panic. having a couple of gl.xxx calls before calling SwapBuffers seems to increase the chance of crashing.
